declare const theme: {
    colors: {
        primary: string;
        accent: string;
        background: string;
        surface: string;
        text: string;
        placeholder: string;
        backdrop: string;
        notification: string;
        border: string;
        surfaceDisabled: string;
        primaryContainer: string;
        secondary: string;
        secondaryContainer: string;
        tertiary: string;
        tertiaryContainer: string;
        surfaceVariant: string;
        error: string;
        errorContainer: string;
        onPrimary: string;
        onPrimaryContainer: string;
        onSecondary: string;
        onSecondaryContainer: string;
        onTertiary: string;
        onTertiaryContainer: string;
        onSurface: string;
        onSurfaceVariant: string;
        onSurfaceDisabled: string;
        onError: string;
        onErrorContainer: string;
        onBackground: string;
        outline: string;
        outlineVariant: string;
        inverseSurface: string;
        inverseOnSurface: string;
        inversePrimary: string;
        shadow: string;
        scrim: string;
        elevation: import("react-native-paper/lib/typescript/types").MD3ElevationColors;
    };
    roundness: number;
    dark: boolean;
    mode?: "exact" | "adaptive";
    animation: {
        scale: number;
        defaultAnimationDuration?: number;
    };
    version: 3;
    isV3: true;
    fonts: import("react-native-paper/lib/typescript/types").MD3Typescale;
};
export default theme;
