import {StyleSheet} from 'react-native';
import {colors} from '../../constants/colors';
import {isWeb, isIpad, leftPadding, CARD_WIDTH} from '../../constants/constant';
import {
  HELVETICA_NEUE_MEDIUM,
  HELVETICA_NEUE_REGULAR,
  HELVETICA_REGULAR,
} from '../../assets/Fonts';

export const styles = StyleSheet.create({
  CardsContainer: {
    justifyContent: 'space-between',
    marginBottom: isWeb ? 0 : 25,
    backgroundColor: colors.white,
    minWidth: CARD_WIDTH,
    alignSelf: 'center',
    borderColor: colors.borderColor,
    borderWidth: isWeb ? 0.4 : 0.5,
    borderTopRightRadius: 8,
    marginRight: leftPadding,
    borderTopLeftRadius: 8,
    shadowColor: colors.black,
    shadowOffset: {width: -2, height: 5},
    shadowOpacity: 0.11,
    shadowRadius: 5,
    elevation: 5,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  checkBoxContainer: {
    marginRight: 5,
    backgroundColor: colors.backgroundColor,
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  checkbox: {
    width: 23,
    height: 23,
    backgroundColor: colors.backgroundColor,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  location: {
    width: isIpad ? 18 : 23,
    height: isIpad ? 18 : 23,
    position: 'absolute',
    left: 18,
    bottom: 10,
  },
  playIcon: {
    width: isIpad ? 18 : 23,
    height: isIpad ? 18 : 23,
    position: 'absolute',
  },
  checkedCheckbox: {
    backgroundColor: colors.secondaryColor,
    borderColor: colors.primaryColor,
    borderWidth: 0.4,
  },
  uncheckedCheckbox: {
    backgroundColor: colors.white,
    borderColor: colors.borderColor,
    borderWidth: 0.4,
  },
  actionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderColor: colors.primaryColor,
    borderWidth: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 14,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  Cards: {
    backgroundColor: colors.backgroundColor,
    borderBottomWidth: isWeb ? 0.4 : 0.5,
    opacity: 1,
    borderColor: colors.borderColor,
    padding: 10,
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
    flex: 1,
  },
  bottomCards: {
    backgroundColor: colors.backgroundColor,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: isWeb ? 0.4 : 0.5,
    justifyContent: 'space-between',
    opacity: 1,
    borderColor: colors.borderColor,
    flex: 1,
    padding: 10,
  },
  statusContainer: {
    marginLeft: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerStatus: {
    borderRadius: 4,
    backgroundColor: colors.primaryColor,
    alignSelf: 'flex-end',
  },
  statusText: {
    fontSize: 11,
    fontFamily: HELVETICA_NEUE_REGULAR,
    paddingHorizontal: 3,
    paddingVertical: 6,
    color: colors.white,
  },
  CardsText: {
    fontSize: 14,
    fontFamily: HELVETICA_NEUE_MEDIUM,
    flexShrink: 1,
    backgroundColor: colors.backgroundColor,
    textDecorationLine: 'underline',
    color: colors.primaryColor,
  },
  dateContainer: {
    marginLeft: 10,
    alignItems: 'flex-end',
    justifyContent: 'center',
    flex: 1,
  },
  dateText: {
    fontSize: 12,
    fontFamily: HELVETICA_NEUE_MEDIUM,
    color: colors.primaryColor,
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardDescriptionContent: {
    marginVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardImageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    margin: 8,
  },
  cardContainer: {
    shadowColor: colors.black,
    borderRadius: 8,
    marginLeft: 11.5,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  descriptionContainer: {
    paddingLeft: 11.5,
    paddingRight: 3.8,
    flex: 1,
  },
  cardImage: {
    width: 120,
    height: 96,
    // aspectRatio: 4 / 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.imageBorderColor,
  },
  cardDescriptionText: {
    fontSize: 11,
    fontFamily: HELVETICA_REGULAR,
    color: colors.accordionDatatableColor,
    marginTop: 10,
    overflow: 'hidden',
    textAlign: 'left',
  },
  rowSpaceBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.4,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  profileImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  iconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 14,
  },
  paddingIcon: {
    padding: 0,
    paddingLeft: 0,
  },
});
