export declare const RIGHT = "right";
export declare const LEFT = "left";
export declare const TOP = "top";
export declare const BOTTOM = "bottom";
export declare const SLIDE_IN_DOWN = "slideInDown";
export declare const SLIDE_OUT_DOWN = "slideOutDown";
export declare const SLIDE_IN_UP = "slideInUp";
export declare const SLIDE_OUT_UP = "slideOutUp";
export declare const SLIDE_IN_RIGHT = "slideInRight";
export declare const SLIDE_OUT_RIGHT = "slideOutRight";
export declare const SLIDE_IN_LEFT = "slideInLeft";
export declare const SLIDE_OUT_LEFT = "slideOutLeft";
export declare const ZOOM_IN = "zoomIn";
export declare const ZOOM_OUT = "zoomOut";
export declare const SIDE_MODAL_MIN_WIDTH: number;
export declare const SIDE_MODAL_MAX_HEIGHT: number;
export declare const DIALOG_MAX_HEIGHT: number;
export declare const DIALOG_MIN_HEIGHT: number;
export declare const DIALOG_MIN_WIDTH: number;
